[tox]
envlist = py310-pytest-{linux, darwin, windows}

[testenv]
basepython = python3.10
envdir = {toxinidir}/.tox_envs/{envname}
package = skip
deps =
    uv==0.11.21
    coverage==7.4.1
allowlist_externals =
    uv
    coverage
setenv =
    RUNTEST_CFG = {env:RUNTEST_CFG}
    UV_CACHE_DIR = {envtmpdir}/uv-cache
commands =
    uv sync --active --all-extras --no-default-groups --group test
    coverage run --source=ayugespidertools -m pytest
    coverage combine
    coverage report
    coverage xml

[testenv:py310-pytest-linux]
description = Run pytest on Linux.
platform = linux
deps =
    {[testenv]deps}
setenv =
    RUNTEST_CFG = {env:RUNTEST_CFG}
    UV_CACHE_DIR = {envtmpdir}/uv-cache
commands =
    {[testenv]commands}

[testenv:py310-pytest-darwin]
inherit_from = py310-pytest-linux
description = Run pytest on Darwin.
platform = darwin
deps =
    {[testenv]deps}
setenv =
    RUNTEST_CFG = {env:RUNTEST_CFG}
    UV_CACHE_DIR = {envtmpdir}/uv-cache

[testenv:py310-pytest-windows]
description = Run pytest on Windows with pywin32.
platform = win32
passenv = USERNAME
deps =
    {[testenv]deps}
    pywin32
setenv =
    RUNTEST_CFG = {env:RUNTEST_CFG}
    UV_CACHE_DIR = {envtmpdir}/uv-cache
